// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDe6kVyhTdCW_66bnCZogEFzi6SvxzyM',
    appId: '1:635439216891:web:ca7901612541baf7bd585e',
    messagingSenderId: '635439216891',
    projectId: 'priority-soft-6824e',
    authDomain: 'priority-soft-6824e.firebaseapp.com',
    storageBucket: 'priority-soft-6824e.appspot.com',
    measurementId: 'G-6M3SXETQ67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxF9TPZI8f5PWWv8v45yhygqvRK4B4R9A',
    appId: '1:635439216891:android:6fbb18ba421e2cbfbd585e',
    messagingSenderId: '635439216891',
    projectId: 'priority-soft-6824e',
    storageBucket: 'priority-soft-6824e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFMnfIaN1OgaYigo2KlKvPll0CTmJt3jI',
    appId: '1:635439216891:ios:8e9a4b3cd5cac590bd585e',
    messagingSenderId: '635439216891',
    projectId: 'priority-soft-6824e',
    storageBucket: 'priority-soft-6824e.appspot.com',
    iosBundleId: 'com.example.prioritySoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFMnfIaN1OgaYigo2KlKvPll0CTmJt3jI',
    appId: '1:635439216891:ios:19dfcbc8a10a46e2bd585e',
    messagingSenderId: '635439216891',
    projectId: 'priority-soft-6824e',
    storageBucket: 'priority-soft-6824e.appspot.com',
    iosBundleId: 'com.example.prioritySoft.RunnerTests',
  );
}
